-- CREATE SCHEMA IF NOT EXISTS sandbox;
-- SET search_path TO public;
-- SHOW search_path;
-- SELECT current_schema(), current_database(), current_user;
-- SELECT * FROM order_demo;

-- CREATE TABLE sandbox.users (
--     id bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
--     email text not null,
--     display_name text not null,
--     is_active boolean not null default true,
--     created_at timestamptz not null default now(),

--     constraint users_email_key unique(email),
--     constraint users_email_shape check(email LIKE '%@%.__%  '),
--     constraint users_name_len check(length(display_name) > 0 and length(display_name) < 100) 
-- )

/* Difference in now(), statement_timestamp(), clock_timestamp()*/

/*
now() (and CURRENT_TIMESTAMP) returns the time the transaction started, and returns the same value for every call inside it. statement_timestamp() is per statement; clock_timestamp() is the actual clock, and moves within a statement. This is usually what you want — every row inserted by one transaction sharing a timestamp is a feature — but it means a long batch job stamps everything with the moment it began, and any "how long did this take" measured with now() 
-- */
-- begin ;
-- select now(), statement_timestamp(), clock_timestamp();
-- select pg_sleep(5);
-- select now(), statement_timestamp(), clock_timestamp();
-- commit;


/* ------------------------------------------------------------------
   DEMO: OVERRIDING SYSTEM VALUE collision on an IDENTITY column
   Shows why GENERATED ALWAYS still lets you shoot yourself in the
   foot if you deliberately override it. Run top to bottom.
   ------------------------------------------------------------------ */

-- CREATE SCHEMA IF NOT EXISTS sandbox;
-- DROP TABLE IF EXISTS sandbox.id_collision_demo;
-- CREATE TABLE sandbox.id_collision_demo (
--     id    bigint PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
--     label text NOT NULL
-- );

-- -- normal inserts: the sequence hands out 1, then 2
-- INSERT INTO sandbox.id_collision_demo (label) VALUES ('auto-a'), ('auto-b');

-- -- caller forces an explicit id, jumping ahead of the sequence.
-- -- GENERATED ALWAYS blocks a plain INSERT into id; OVERRIDING SYSTEM VALUE
-- -- is the on-purpose escape hatch, and it does NOT advance the sequence.
-- INSERT INTO sandbox.id_collision_demo (id, label)
-- OVERRIDING SYSTEM VALUE VALUES (5, 'manual-5');

-- -- rows so far: 1, 2, 5   ...   but the sequence still thinks it's at 2
-- SELECT * FROM sandbox.id_collision_demo ORDER BY id;
-- SELECT currval(pg_get_serial_sequence('sandbox.id_collision_demo','id')) AS seq_is_at;

-- -- keep doing normal inserts: 3, 4 are fine...
-- INSERT INTO sandbox.id_collision_demo (label) VALUES ('auto-c');   -- id 3
-- INSERT INTO sandbox.id_collision_demo (label) VALUES ('auto-d');   -- id 4

-- -- ...then the sequence reaches 5, which the manual row already took:
-- INSERT INTO sandbox.id_collision_demo (label) VALUES ('auto-e');
-- -- ERROR:  duplicate key value violates unique constraint "id_collision_demo_pkey"
-- -- DETAIL:  Key (id)=(5) already exists.
-- -- The bug surfaces N inserts later, nowhere near the INSERT that caused it.

-- -- fix: shove the sequence past the highest id actually in the table
-- SELECT setval(
--     pg_get_serial_sequence('sandbox.id_collision_demo','id'),
--     (SELECT max(id) FROM sandbox.id_collision_demo)
-- );
-- INSERT INTO sandbox.id_collision_demo (label) VALUES ('auto-e-again');  -- id 6, OK

-- SELECT * FROM sandbox.id_collision_demo ORDER BY id;
-- DROP TABLE sandbox.id_collision_demo;

-- Lesson: GENERATED ALWAYS makes the override explicit, not impossible.
-- The moment you use OVERRIDING SYSTEM VALUE you own the job of keeping the
-- sequence ahead of your manual ids. GENERATED BY DEFAULT / serial would have
-- let this happen with no OVERRIDING keyword at all.


BEGIN;
  INSERT INTO sandbox.users (email, display_name) VALUES ('p@y.co', 'P');
  SAVEPOINT before_risky;
  INSERT INTO sandbox.users (email, display_name) VALUES ('p@y.co', 'P2');  -- ERROR
  ROLLBACK TO SAVEPOINT before_risky;    -- transaction is usable again
  SELECT count(*) FROM sandbox.users;    -- works; first insert survives
COMMIT;