 /* SCHEMA Creation*/
-- CREATE SCHEMA IF NOT EXISTS sandbox;
-- CREATE TABLE sandbox.users (
--         id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--         email           text NOT NULL UNIQUE,
--         created_at      timestamptz NOT NULL DEFAULT now(),
--         is_active       boolean NOT NULL DEFAULT true,
--         account_balance numeric(12,2) NOT NULL DEFAULT 0,
--         metadata        jsonb NOT NULL DEFAULT '{}'::jsonb
--     );

    -- INSERT INTO sandbox.users (email, account_balance, metadata) VALUES
    -- ('john.doe@example.com', 1000.00, '{"department": "Engineering"}'::jsonb);

-- 1. Coercion failure (unknown literal -> numeric, but not parseable)
INSERT INTO sandbox.users (email, account_balance)
VALUES ('a@b.com', 'fifteen hundred');
-- ERROR: invalid input syntax for type numeric: "fifteen hundred"

-- 2. True type mismatch (no coercion path exists at all)
INSERT INTO sandbox.users (email, account_balance)
VALUES ('a@b.com', true);
-- ERROR: column "account_balance" is of type numeric but expression is of type boolean

-- 3. Unique violation (your UNIQUE on email) -- rerun your successful insert
INSERT INTO sandbox.users (email) VALUES ('john.doe@example.com');
-- ERROR: duplicate key value violates unique constraint "users_email_key"

-- 4. NOT NULL violation
INSERT INTO sandbox.users (email) VALUES (NULL);
-- ERROR: null value in column "email" ... violates not-null constraint

-- 5. Identity column -- can you override it?
INSERT INTO sandbox.users (id, email) VALUES (999, 'x@y.com');
-- ERROR: cannot insert a non-DEFAULT value into column "id"
-- (this is GENERATED ALWAYS earning its keep -- GENERATED BY DEFAULT would allow it)

