-- psql -h localhost -p 5432 -U ronitroy -d learningdb -f SQL/aggregate.sql
SELECT MAX(temp_lo) FROM weather;
-- AGGREAGTE CAN NOT USE WITH WHERE CLAUSE
-- SELECT MAX(temp_lo) FROM weather WHERE city = 'San Francisco';
-- USING A SUB QUERY TO GET THE MAX TEMP_LO FOR SAN FRANCISCO
SELECT CITY FROM WEATHER WHERE temp_lo = ( SELECT MAX(temp_lo) FROM WEATHER );
-- AGGREGATE FUNCTION WITH GROUP BY CLAUSE
SELECT CITY, COUNT(*), MAX(TEMP_LO) FROM WEATHER GROUP BY CITY;
-- WE CAN FILTER THE GROUP ROWS WITH HAVING CLAUSE
SELECT CITY, COUNT(*), MAX(TEMP_LO) FROM WEATHER GROUP BY CITY HAVING MAX(TEMP_LO) < 40;
-- LIKE CLAUSE CAN BE USED WITH AGGREGATE FUNCTION
SELECT CITY, COUNT(*), MAX(TEMP_LO) FROM WEATHER WHERE CITY LIKE 'S%' GROUP BY CITY;

-- WHERE VS HAVING CLAUSE
-- WHERE CLAUSE IS USED TO FILTER ROWS BEFORE AGGREGATE FUNCTION IS APPLIED
-- HAVING CLAUSE IS USED TO FILTER GROUPS AFTER AGGREGATE FUNCTION IS APPLIED

-- FILTER CLAUSE
SELECT CITY, COUNT(*) FILTER(WHERE temp_lo < 45), MAX(TEMP_LO) FROM WEATHER GROUP BY CITY;